title: praxis
email: praxis.nyc@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Decolonize your attention
baseurl: ''
url: 'https://praxis.nyc/'
twitter_username: nonlinear
github_username: nonlinear
destination: docs

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock


team: 
  - name: Nicholas Frota
    email: info@nicholasfrota.com
    description: the anagram of my name is anarchist fool
    avatar: 
    social:
      - name: site
        url: https://nonlinear.nyc
      - name: mastodon
        url: https://mastodon.social/@nonlinear
      - name: twitter
        url: https://twitter.com/nonlinear
      - name: instagram
        url: https://instagram.com/nonlinear

  - name: Lyndsey Richardson
    email: richar11489@gmail.com
    description: 
    avatar: 
    # social:
    #   - name: site
    #     url: https://praxis.nyc
    #   - name: mastodon
    #     url: https://mastodon.social/@nonlinear
    #   - name: twitter
    #     url: https://twitter.com/nonlinear
      - name: instagram
        url: https://instagram.com/marierichson



